# Generated by Django 6.0 on 2026-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='assets/images/profile.png', upload_to='profiles/'),
        ),
    ]
