# Generated by Django 6.0 on 2026-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_jobseekerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/profile.png', upload_to='profiles/'),
        ),
    ]
